### ISSUE TITLE
[Feature Request] Compatibility with Passive Shield

### ISSUE THREAD

**Issue by SplendidAlakey** [xanthian/variant_shields#1]
Hello, I'd like to request compatibility with the [Passive Shield](https://www.curseforge.com/minecraft/mc-mods/passive-shield-fabric) mod.

The dev of that mod says that mods need to "[extend the ShieldItem in their Shield class](https://github.com/ricksouth/serilum-mc-mods/issues/770#issuecomment-1223834199)".

A couple of working examples: [MC Dungeons Weapons](https://www.curseforge.com/minecraft/mc-mods/mcdw), [The Bumblezone](https://www.curseforge.com/minecraft/mc-mods/the-bumblezone-fabric).

**Comment by xanthian** [comment]
Those 2 mods don't use fabric shield lib so extend they vanilla ShieldItem.
My shields extend FabricShieldItem as it was far easier to implement the shields.

Would be good if Passive Shield could work with fabric shield lib also

I'll look at changing it possibly in a later release, but doing so may delete existing shields in peoples inventories..

**Comment by xanthian** [comment]
I've raised it on Passive Shield git issues, seems a simple fix on that end tbh.
https://github.com/ricksouth/serilum-mc-mods/issues/1348

**Comment by xanthian** [comment]
apparently this should work now, untested however.

**Comment by turnerlewis** [comment]
It does not. I have the passive shield mod working for vanilla shields, as well as knightmetal shield from twilight forest, but not the variant shields. They do not hide like the others do.
