### ISSUE TITLE
Piglins are not spawning 

### ISSUE THREAD

**Issue by feliday** [xanthian/variant_shields#5]
playing 1.20.1 with the latest fabric version 2.0.1

i noticed that piglins were not spawning at all. brutes and zombified ones were, but piglins were missing. removed all mods other than the mod itself, fabric api, and the library. i cannot find, spawn with spawn eggs, or command summon any standard piglin with this mod loaded. they are effectively removed from the game

**Comment by xanthian** [comment]
2.01 is not the latest
2.1 is.
If not, please update.
not sure where you have downloaded it from as 2.01 is archived due to this bug

tested on 2.1 working perfectly fine.
![image](https://github.com/xanthian/variant_shields/assets/7688001/24177504-be41-4a46-82c0-6c44eb7ad6dc)

**Comment by feliday** [comment]
i have no clue how i got 2.0.1 instead of 2.1? i was absolutely certain i downloaded the latest version off curseforge. thank you for alerting me, i got the right file this time. sorry for the trouble!
